### ISSUE TITLE
Ticket #2 - Bug dans la gestion des prolongations de prêt

### ISSUE THREAD

**Issue by Caprog** [llecorps/Library2#5]
Nous avons découvert un bug de la gestion des prolongations de prêt. En effet, un usager peut prolonger un prêt après la date butoir. Il ne doit pas être possible pour l’usager de prolonger un prêt si la date de fin de prêt est dépassée.

La correction de cette anomalie est urgente car elle nous pose de gros problèmes de gestion. Actuellement beaucoup trop de personnes attendent le mail de rappel pour prolonger leur prêt. Cela entraîne la plainte de certains usagers à qui nous avions communiqué une date de retour et qui se déplacent en bibliothèque pour rien car le prêt a été prolongé a posteriori.

Je vous demande de livrer une nouvelle version de l’application au plus vite afin de corriger ce bug mais sans inclure nos autres demandes en cours. Nous souhaiterions pouvoir mettre en production rapidement sans avoir à faire de recette sur les autres évolutions demandées.

**Comment by llecorps** [comment]
La solution a été livré sur la branche git HotFix v1.5.1.
La correction comprend un batch java schédulé qui mettra à jour automatiquement le boolean "prolongation" à False, une fois le terme échu,
Le bouton "prolongation" ne sera plus disponible dans l'espace utilisateur.
